version: '3'
services:
  backend:
    image: my-java-app
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/NovelsHobby
      SPRING_DATASOURCE_USERNAME: kim
      SPRING_DATASOURCE_PASSWORD: as9906
      SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES: elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kim
      POSTGRES_PASSWORD: as9906
      POSTGRES_DB: NovelsHobby
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - "discovery.type=single-node"
    volumes:
      - es-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  pg-volume:
    external: true
  es-volume:
    external: true
